### ISSUE TITLE
Clarify the (implicit) scope of some use-cases

### ISSUE THREAD

**Issue by luisbran** [zkpstandard/zkreference#12]
**Proposed contribution:** The last paragraph in section 2.2 says “digital money based applications belong to the first model” [public verifiable as a requirement]. This assertion appears implicitly scoped in a too narrow subset of conceivable applications about digital money. Conversely, one could consider a scenario where Alice wants to convince Bob, in a non-transferable way, that Alice bought something from Charlie. Consider clarifying better the scope of examples vs. the scope of areas of application.

**Related locations:** Section 3.2

**Proposed contributors:** _Needs contributors_

**Contribution context:** Proposed in the "[NIST comments on the initial ZKProof documentation](https://community.zkproof.org/uploads/short-url/pfzbGwLRFZBmccRW17ngZS0c4h1.pdf#pdfbkmk%3Arevcom%3AC15.3)" (April 06, 2019) --- item C15.

**Comment by 0xKarl98** [comment]
I would appreciate that if I could take part in this proposal 
Thanks in advance

**Comment by daniben31** [comment]
Hi @DecentrilizedMan feel free to write about this as well. I would be happy to collaborate if you want to.

**Comment by 0xKarl98** [comment]
@daniben31  thanks Daniel , I have accepted this issue , will work it out as soon as possible ~

**Comment by 0xKarl98** [comment]
@daniben31  I just submitted the contribution , check it out ～
