### ISSUE TITLE
Compare circuits vs. R1CS

### ISSUE THREAD

**Issue by luisbran** [zkpstandard/zkreference#13]
**Proposed contribution:** The “security/theory” track is mentioning Boolean circuits but not R1CS. The “implementation” track is focused on R1CS without explaining why/when it is preferable to a circuit representation. Consider explaining better (in the “security” track) what is R1CS. Consider introducing and exemplifying a circuit-to-R1CS translation and/or vice-versa. Consider clarifying better in the “implementation” track why the focus is on R1CS, for example compared with circuits.

**Related locations:** Chapters 1 (security/theory) and 2 (implementation)

**Proposed contributors:** _Needs contributors_

**Contribution context:** Proposed in the "[NIST comments on the initial ZKProof documentation](https://community.zkproof.org/uploads/short-url/pfzbGwLRFZBmccRW17ngZS0c4h1.pdf#pdfbkmk%3Arevcom%3AC10.3)" (April 06, 2019) --- item C10.

**Comment by hasinitg** [comment]
I would like to work on this contribution. 

Thanks,
Hasini.

**Comment by 0xKarl98** [comment]
IM willing to be part of this !

**Comment by daniben31** [comment]
I have invited both of you to the contributors team, as soon as you accept we will assign this issue to both of you. Looking forward to the contribution!

**Comment by hasinitg** [comment]
Thanks @daniben31. I have accepted it.

**Comment by daniben31** [comment]
For the record, @DecentrilizedMan just submitted an initial document:

[contributor_tex (1).pdf](https://github.com/zkpstandard/zkreference/files/3414459/contributor_tex.1.pdf)
