### ISSUE TITLE
Introduction to interactive zero-knowledge proofs

### ISSUE THREAD

**Issue by daniben31** [zkpstandard/zkreference#18]
**Proposed contribution:** An introduction to advantages and disadvantages of interactive zero-knowledge proofs relative to non-interactive ones, and a discussion of scenarios and applications where interactive protocols may be particularly suitable or relevant.

**Related locations:** Security section

**Proposed contributors:** Justin Thaler and Yael Kalai (and further contributors)

**Contribution context:** Discussed during the "Interactive Zero Knowledge" brekout session in the 2nd ZKProof Workshop

**Comment by daniben31** [comment]
@starzyp I beleive that Justin Thaler is collecting contributions that came out around that session and will submit the full contribution as related to this issue.

Did Justing reach out to you?

**Comment by starzyp** [comment]
@daniben31 Yes, he did. I'll send a draft to him first.
